src/ZoolandiaMVC/Models/Animal.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ZoolandiaMVC.Models
{
    public class Animal
    {
        public int ID { get; set; }

        [RegularExpression(@"^[A-Z]+[a-zA-Z''-'\s]*$")]
        [StringLength(60, MinimumLength = 3)]
        public string Name { get; set; }
        [Range(1, 100)]
        public int IdHabitat { get; set; }
        [Range(1, 100)]
        public int IdSpecies { get; set; }
    }
}

src/ZoolandiaMVC/Controllers/AnimalController.cs
using System.Linq;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using ZoolandiaMVC.Models;
using ZoolandiaMVC.ViewModels;
using System;
using System.Collections.Generic;
using Microsoft.AspNet.Http;
using System.IO;
using Microsoft.Net.Http.Headers;

namespace ZoolandiaMVC.Controllers
{
    public class AnimalController : Controller
    {
        private ApplicationDbContext _context;

        public AnimalController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: Animals
        public IActionResult Index(string searchString)
        {

            // Create functionality for searching
            var animals = from a in _context.Animal
                          select a;

            

            // access the database and get info for the animal's name and habitat
            var AnimalInfo =
                (from animal in _context.Animal
                 join habitat in _context.Habitat
                 on animal.IdHabitat equals habitat.ID

                 join species in _context.Species
                 on animal.IdSpecies equals species.ID

                 //basically means 'create new' based on search results
                 select new AnimalDataViewModel
                 {
                     ID = animal.ID,
                     animal = animal.Name,
                     animalHabitatName = habitat.Name,
                     animalSpecies = species.CommonName

                 }).ToList();

            // Filter the list for search results
            if (!String.IsNullOrEmpty(searchString))
            {
                var filteredAnimalInfo = AnimalInfo.Where(item => item.animal == searchString);
                return View(filteredAnimalInfo);
            }

            // Pass that information to the view
            return View(AnimalInfo);
        }

        // GET: Animals/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            // Get the specifice animal
            Animal animal = _context.Animal.Single(m => m.ID == id);

            // Get Document table from the database
           
            var docs = (from d in _context.Document
                        orderby d.FileName
                        select new Document
                        {}).ToList();

            DocumentDetailsViewModel vm = new DocumentDetailsViewModel()
            {
                Documents = docs,
                ID = animal.ID,
                IdHabitat = animal.IdHabitat,
                IdSpecies = animal.IdSpecies,
                Name = animal.Name
            };
            return View(vm);
        }

        [HttpPost]
        public IActionResult Details(IFormFile file, DocumentDetailsViewModel docViewModel)
        {
            using (var dbContext = new ApplicationDbContext())
            {
                if (file != null && file.Length > 0)
                    try
                    {
                        var fileName = ContentDispositionHeaderValue.Parse(file.ContentDisposition).FileName.Trim('"');
                        using (var reader = new StreamReader(file.OpenReadStream()))
                        {
                            string contentAsString = reader.ReadToEnd();
                            byte[] bytes = new byte[contentAsString.Length * sizeof(char)];
                            System.Buffer.BlockCopy(contentAsString.ToCharArray(), 0, bytes, 0, bytes.Length);
                            var fileType = file.ContentType;
                            Document doc = new Document()
                            {
                                Title = docViewModel.Title,
                                FileName = fileName,
                                Contents = bytes,
                                ContentType = fileType,
                                UploadDate = DateTime.Now,
                                UploadUserId = "williamhickok11@gmail.c0m"
                            };

                            dbContext.Document.Add(doc);
                            dbContext.SaveChanges();
                        }

                        ViewBag.Message = "File uploaded successfully";

                    }
                    catch (Exception ex)
                    {
                        ViewBag.Message = "ERROR:" + ex.Message.ToString();
                    }

                ////go back to index and the new doc should show
                //var docs = from d in dbContext.Document
                //           orderby d.FileName
                //           select d;

                DocumentDetailsViewModel vm = new DocumentDetailsViewModel()
                {
                    //Documents = docs.ToList()
                };
                return View(vm);
            }
        }


        // GET: Animals/Create
        public IActionResult Create()
        {
            var AnimalFullInfo =
                (from animal in _context.Animal
                 join habitat in _context.Habitat
                 on animal.IdHabitat equals habitat.ID

                 join species in _context.Species
                 on animal.IdSpecies equals species.ID

                 //basically means 'create new' based on search results
                 select new AnimalDataViewModel
                 {
                     ID = animal.ID,
                     animal = animal.Name,
                     animalHabitatName = habitat.Name,
                     animalSpecies = species.CommonName,
                     habitatId = habitat.ID,
                     speciesId = species.ID

                 }).ToList();

            var habitatNameList = new List<string>();
            foreach (var item in AnimalFullInfo)
            {
                habitatNameList.Add(item.animalHabitatName);
            }
            ViewData["habitatList"] = new SelectList(habitatNameList);

            // Pass that information to the view
            return View(AnimalFullInfo);
        }

        // POST: Animals/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Animal animal)
        {
            if (ModelState.IsValid)
            {
                _context.Animal.Add(animal);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(animal);
        }

        // GET: Animals/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Animal animal = _context.Animal.Single(m => m.ID == id);
            if (animal == null)
            {
                return HttpNotFound();
            }
            return View(animal);
        }

        // POST: Animals/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Animal animal)
        {
            if (ModelState.IsValid)
            {
                _context.Update(animal);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(animal);
        }

        // GET: Animals/Delete/5
        [ActionName("Delete")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Animal animal = _context.Animal.Single(m => m.ID == id);
            if (animal == null)
            {
                return HttpNotFound();
            }

            return View(animal);
        }

        // POST: Animals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            Animal animal = _context.Animal.Single(m => m.ID == id);
            _context.Animal.Remove(animal);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

src/ZoolandiaMVC/Views/Animal/Create.cshtml
@model ZoolandiaMVC.Models.Animal

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-controller="Movies" asp-action="Index">
    <p>
        Genre: @Html.DropDownList("habitatList", "Give me all of them!")
        Title: <input type="text" name="SearchString">
        <input type="submit" value="Filter" />
    </p>
</form>




<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Animal</h4>

        

        <hr />
        <div asp-validation-summary="ValidationSummary.ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="IdHabitat" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="IdHabitat" class="form-control" />
                <span asp-validation-for="IdHabitat" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="IdSpecies" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="IdSpecies" class="form-control" />
                <span asp-validation-for="IdSpecies" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

src/ZoolandiaMVC/Views/Animal/Delete.cshtml
@model ZoolandiaMVC.Models.Animal

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Animal</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdHabitat)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdHabitat)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdSpecies)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdSpecies)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

src/ZoolandiaMVC/Views/Animal/Details.cshtml
@model ZoolandiaMVC.ViewModels.DocumentDetailsViewModel

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Animal</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdHabitat)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdHabitat)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdSpecies)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdSpecies)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>

    @using (Html.BeginForm("Details", "Animal", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <label for="file">File Upload:</label>
        <br />
        @Html.Label("File Name:   ")@Html.TextBoxFor(model => model.Title)

        
        <input type="file" name="file" id="file" />
        <br>
        <input type="submit" value="Upload File" />
        <br>
    }

</div>
<p>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</p>

src/ZoolandiaMVC/Views/Animal/Edit.cshtml
@model ZoolandiaMVC.Models.Animal

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Animal</h4>
        <hr />
        <div asp-validation-summary="ValidationSummary.ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="ID" />
        <div class="form-group">
            <label asp-for="IdHabitat" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="IdHabitat" class="form-control" />
                <span asp-validation-for="IdHabitat" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="IdSpecies" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="IdSpecies" class="form-control" />
                <span asp-validation-for="IdSpecies" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

src/ZoolandiaMVC/Views/Animal/Index.cshtml
@model IEnumerable<ZoolandiaMVC.ViewModels.AnimalDataViewModel>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<form asp-controller="Animal" asp-action="Index">
    <p>
        Title: <input type="text" name="SearchString">
        <input type="submit" value="Filter" />
    </p>
</form>

<p>
    <a asp-action="Create">Create New</a>
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.animalHabitatName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.animalSpecies)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.animal)
        </th>
        <th></th>
    </tr>
    
@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.animalHabitatName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.animalSpecies)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.animal)
        </td>
        <td>
            <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
            <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
            <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
        </td>
    </tr>
}
</table>